version: "3.8"

services:
  my-app:
    image: web-img # Ensure this image exists or add 'build: .'
    container_name: u-app
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - "4040:${PORT}"
    networks:
      - app-network
    depends_on:
      - mysql-db

  mysql-db:
    image: db-img
    container_name: u-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:


volumes:
  mysql_data:
