apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: kaniko-builder
spec:
  containers:
  - name: kaniko-web
    image: gcr.io/kaniko-project/executor:latest
    command:
    - /kaniko/executor
    args:
    - "--context=dir://workspace/solution_plus_project/application"
    - "--dockerfile=workspace/solution_plus_project/application/Dockerfile"
    - "--destination=salmahesham1114/solution_plus_project/web-img:latest"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker

  - name: kaniko-db
    image: gcr.io/kaniko-project/executor:latest
    command:
    - /kaniko/executor
    args:
    - "--context=dir://workspace/solution_plus_project/application"
    - "--dockerfile=workspace/solution_plus_project/application/Docker-mysql"
    - "--destination=salmahesham1114/solution_plus_project/db-img:latest"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker

  volumes:
  - name: kaniko-secret
    secret:
      secretName: docker-config
