apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE USER IF NOT EXISTS 'salma'@'%' IDENTIFIED WITH mysql_native_password BY 'pass';
    GRANT ALL PRIVILEGES ON *.* TO 'salma'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
