apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_USER: "c2FsbWE="  # Base64-encoded value of "salma"
  DB_PASSWORD: "cGFzcw=="  # Base64-encoded value of "pass"
  DB_ROOT_PASSWORD: "cGFzcw=="  # Base64-encoded value of "pass"
