apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_USER: "c2FsbWE="  # "salma" Base64-encoded
  MYSQL_PASSWORD: "cGFzcw=="  # "pass" Base64-encoded
  MYSQL_ROOT_PASSWORD: "cGFzcw=="  # "pass" Base64-encoded
