apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    service: mysql-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/tmp/volumes"
