apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
   service: mysql-data
  name: mysql-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
