    - name: Download Trivy binary
      uri:
        url: "https://github.com/aquasecurity/trivy/releases/download/v0.60.0/trivy_0.60.0_Linux-64bit.tar.gz"
        dest: /tmp/trivy.tar.gz
        method: GET
      register: download_result

    - name: Check if download was successful
      fail:
        msg: "Failed to download Trivy binary: {{ download_result }}"
      when: download_result.status is not defined or download_result.status != 200

    - name: Extract Trivy binary
      unarchive:
        src: /tmp/trivy.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Check if Trivy binary was extracted
      stat:
        path: /tmp/trivy
      register: trivy_binary_stat
      failed_when: not trivy_binary_stat.stat.exists

    - name: Move Trivy binary to /usr/local/bin
      command: mv /tmp/trivy /usr/local/bin/trivy
      args:
        creates: /usr/local/bin/trivy

    - name: Verify Trivy installation
      command: trivy --version
      register: trivy_version
    - debug:
        var: trivy_version.stdout