- name: Ensure Prometheus user exists
  user:
    name: prometheus
    system: yes
    shell: /bin/false

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.47.0/prometheus-2.47.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install Prometheus
  copy:
    src: "/tmp/prometheus-2.47.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
    remote_src: yes 
  loop:
    - prometheus
    - promtool

- name: Copy Prometheus configuration
  copy:
    src: files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Create Prometheus systemd service
  copy:
    src: files/prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Reload systemd and start Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes